### ISSUE TITLE
Kompatibilita s 2.4

### ISSUE THREAD

**Issue by landsman** [jahudka/tracy-bar-ajax#2]
Ahoj,

rád bych tohle, či obdobné řešení zanesl do mého portu na Tracy pro Opencart, kde jsou mraky ajaxových požadavků - https://github.com/BurdaPraha/oc_tracy

Nevíš, co by nyní bylo třeba pro tenhle support mimo nette?

díky

**Comment by jahudka** [comment]
Ahoj, pro kompletnost - řešili jsme po Slacku, problém byl s pozdním startem session; nicméně i tady pro úplnost zopakuju, že jahudka/tracy-bar-ajax je obsolete, protože Tracy už AJAX obstarává nativně :-)
